language: node_js

node_js:

   - "10.15.3"

branches:

   only:

      - master


before_script:

   - npm install -g @angular/cli
   - npm install -g bower
   - npm install -g firebase-tools


script:
  
   - cd client
   - npm install
   - npm run build-ci

notifications:
   slack:
      rooms:
      - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#code
      - engagelab:SQxy4szJPRe7nn1w8Thn4ygl#beta-blocks-dev